### ISSUE TITLE
mixins的疑问

### ISSUE THREAD

**Issue by Basakerone** [lentoo/vue-cli3-project#2]
作者你好，我是一个新手，请问一下，如果store模块或页面划分，我该怎么写复用方法，如mixins的news-mixin
![123](https://user-images.githubusercontent.com/17926247/52047379-d8d08b00-2583-11e9-9d43-0d71c9e1d2c5.png)
我尝试着这样写，不过有些问题，麻烦指教一下。

**Comment by lentoo** [comment]
比如多个页面有用到  getNews 方法，就可以将 这个方法写在 news-mixin.js 里，然后其它页面想要使用，直接引入这个news-mixin.js 就有getNews 这个方法了。不知道这么说你能理解不？

**Comment by Basakerone** [comment]
谢谢作者回答。这个我能理解。我想问的是如果store按分页或划分如上图所示，作者你的news模块被我划分到了home下的news文件夹，store根目录的index引用home中的index然后引用news下的index。然后运行的时候报错unknown action type: NEWS_LIST和unknown getter: getNewsResponse。请问我该怎么改写？原谅我上面没有清楚的表达。谢谢耐心回答。

**Comment by lentoo** [comment]
上面的截图好像没什么问题，能看下home/index.js 和 news/index.js 的代码吗？

**Comment by Basakerone** [comment]
-----------------------------
home:
-----------------------------
import news from './news'

export default {
    news
}

-----------------------------
news:
-----------------------------
import actions from './actions'
import mutations from './mutations'
import getters from './getters'

const state = {
    NEWS_LIST : []
}

export default {
	namespaced: true,
	state,
	actions,
    mutations,
    getters
}

**Comment by lentoo** [comment]
你加了 namespaced: true, 应该通过命名空间去访问 这个 news store ，或者你可以把这个 namespaced 去掉

**Comment by Basakerone** [comment]
谢谢解答。自己没太了解这些就问了作者，打扰了。。。
